language: cpp
compiler: gcc
env:
  global:
  - ROS_DISTRO=hydro
notifications:
  email:
  - francois.keith@gmail.com
branches:
  only:
  - master
  - master2
  - groovy
script: ./.travis/run build
after_success: ./.travis/run after_success
after_failure: ./.travis/run after_failure
before_install: ./.travis/run dependencies/catkin; ./.travis/run before_install

