language: cpp
compiler: gcc
env:
  matrix: # this section is for the Debian branch only
  - DIST=precise
notifications:
  email:
  - francois.keith@gmail.com
branches:
  only:
  - master
  - groovy
script: ./.travis/run build
after_success: ./.travis/run after_success
after_failure: ./.travis/run after_failure
before_install: ./.travis/run dependencies/catkin ./.travis/run before_install

